### ISSUE TITLE
Consider merging Compilers and Simulators Top-level Tasks

### ISSUE THREAD

**Issue by nathanshammah** [unitaryfund/metriq-app#519] opened 2022-04-18 15:14 UTC
Most compilers are also simulators and viceversa, simulators contain compilers to increase their efficiency and optimize against certain metrics. I understand that by compilers we also mean compilers that may be thought to compile on quantum hardware only, but at some level they contain a quantum circuit simulation / representation.  

As a user, I am sometimes confounded of whether a compiler should be a simulator or vice versa. For example, `qutip-qip` is a quantum circuit simulator (with pulse-level simulation) that contains a compiler.

**Comment by crazy4pi314** [comment] 2022-04-19 01:00
@WrathfulSpatula I don't think I have ever expressed anything like this :P

I think it is fair to keep the buckets as is, and things can live in more than one if the have the functionality?

**Comment by WrathfulSpatula** [comment] 2022-04-19 17:09
@crazy4pi314 Sorry, I imagined it. Never mind.

Notwithstanding, my argument against the issue remains as I wrote it above. I think there might be a quasi-common belief or intuition that simulation is basically a special case of general quantum computer compilation, but I don't think it is actually is, as a simulator developer.

**Comment by crazy4pi314** [comment] 2022-04-19 18:07
I agree with you @WrathfulSpatula, and would only suggest that tools that can do both (like QDK) should show up on both lists.

**Comment by WrathfulSpatula** [comment] 2022-04-19 23:09
QDK compilation vs. QDK runtime simulation could be entered under the respective topics, by design. This would be on a per-task basis, and both types of task could occur in the same submission. We'd want to combine the top-level task categories only if the results were topically common; I don't think they are. However, the issue ticket can serve to remind us to look at whether the two are distinct or common.

**Comment by WrathfulSpatula** [comment] 2022-10-20 19:15
I think we can close this. Like I said in my last comment, we can differentiate between compilation vs. runtime, but allowing multiple parent tasks isn't in the design of the task hierarchy, and I don't consider this issue (or anything else we've come across) to be compelling enough to change that aspect of the fundamental design of the hierarchy.

**Closed by WrathfulSpatula** 2022-10-20 19:15 UTC
Labels: enhancement, question, userstory, taxonomy, task-classification
