### ISSUE TITLE
Editing results throw TypeError on submit 

### ISSUE THREAD

**Issue by karlaspuldaro** [unitaryfund/metriq-app#897] opened 2024-01-30 22:31 UTC
<img width="622" alt="Screenshot 2024-01-30 at 5 17 54 PM" src="https://github.com/unitaryfund/metriq-app/assets/25207344/adf8b563-51c0-4aa1-ae63-a4c2a97cdc99">

This happens when clicking `submit` and `submit & repeat` buttons in the dialog to edit results.
Browser: Chrome
OS: MacOS

**Comment by WrathfulSpatula** [comment] 2024-04-23 17:46
I've confirmed that this has since been addressed in the code, Karla. Please reopen the issue, if you have any more problems.

**Closed by WrathfulSpatula** 2024-04-23 17:46 UTC
